name: registro_vehicular
description: Registro Vehicular

publish_to: 'none' # Remove
version: 1.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^9.2.0
  path_provider: ^2.0.2
  open_file: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
